services:
  - docker
dist: focal
virt: vm
group: edge
arch:
  - arm64-graviton2
script:
  - sudo apt-get remove --purge docker-compose -y
  - sudo file /usr/local/bin/docker-compose
  - sudo rm -rf /usr/local/bin/docker-compose
  - sudo apt-get install -y bats curl docker-compose
  - echo $PATH
  - sudo cp /usr/bin/docker-compose /usr/local/bin/
  #- export PATH=/usr/bin/:$PATH
  #- sudo apt-get install -y bats
  - make all
